spring:
  application:
    name: springai-bootcamp-demo
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:chatbot.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma4:e4b
          temperature: 0.7